### ISSUE TITLE
Modeltime H2O Roadmap

### ISSUE THREAD

**Issue by mdancho84** [business-science/modeltime.h2o#1]
A working roadmap for developing an H2O extension for modeltime. 

## MVP Package:

- [X] Create Package Structure
- [x] Develop MVP Algorithms (#2) - Get basic use-cases from Shafi, Develop MVP algorithms, Test on several datasets 
- [x] Develop R
    - [x] Dependencies (#3 )
    - [x] Core `automl_reg()` algorithm (#4)
    - [x] Saving/Loading Models / Workflows (#5)
- [x] Create Tests (#7)
- [x] Automate Tests with GitHub Actions (#8)
- [x] Make AWESOME README (#9)
- [x] Add Vignettes - Getting Started (#10)
- [x] Make Hex Logo (#11)
- [x] Add Pkgdown Documentation (#12)
- [x] Finalize DESCRIPTION
- [x] Send to CRAN

## Future efforts

- [ ] More Efficient Refitting - Use parameters from specific model rather than fully re-training AutoML (#14)
- [x] H2O Leaderboard - Allow users to view the Leaderboard and swap out models (#15)
